# Default value of indentation
defaultIndent: "  "

indentRules:
   myenvironment: "  "
   anotherenvironment: "  " 
   chapter: " "
   section: " "
   item: "    "
   myitem: "        "

modifyLineBreaks:
    oneSentencePerLine:
        manipulateSentences: 1
        sentencesFollow:
            blankLine: 0
